### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by mibby** [Fupery/ArtMap#30]
PaperSpigot dev 963 (MC 1.11)
ArtMap v2.5

```
[12:28:23] [Server thread/WARN]: [ArtMap] Task #188150 for ArtMap v2.5 generated an exception
java.lang.NullPointerException
	at me.Fupery.ArtMap.Easel.Easel.lambda$null$0(Easel.java:239) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.11.jar:git-Paper-963]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:355) [patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:807) [patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.jar:git-Paper-963]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
```

**Comment by Fupery** [comment]
What were you doing when this happened? I've not been able to replicate it.

**Comment by mibby** [comment]
I am not able to reproduce and haven't seen the error since updating to version 2.5.7. I will re-open if I see the error again and see if I can find steps to reproduce. It may have been fixed with ArtMap throwing out update events more frequently.
