### ISSUE TITLE
SQLiteException / Server (Java) Crash

### ISSUE THREAD

**Issue by mibby** [Fupery/ArtMap#31]
PaperSpigot dev 968 (MC / Spigot 1.11)
ArtMap v2.5

@Fupery Getting some errors and server crashing caused by ArtMap. :(

```
[18:59:45] [Craft Scheduler Thread - 441/WARN]: [ArtMap] Database error, Check /plugins/ArtMap/error.log for details.
[18:59:45] [Craft Scheduler Thread - 441/WARN]: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (Connection is closed)
[18:59:45] [Craft Scheduler Thread - 441/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:909)
[18:59:45] [Craft Scheduler Thread - 441/WARN]: 	at org.sqlite.core.CoreStatement.internalClose(CoreStatement.java:115)
[18:59:45] [Craft Scheduler Thread - 441/WARN]: 	at org.sqlite.jdbc3.JDBC3Statement.close(JDBC3Statement.java:35)
[18:59:45] [Craft Scheduler Thread - 441/WARN]: 	at org.sqlite.jdbc4.JDBC4Statement.close(JDBC4Statement.java:27)
[18:59:45] [Craft Scheduler Thread - 441/WARN]: 	at me.Fupery.ArtMap.IO.ArtDatabase$QueuedQuery.close(ArtDatabase.java:326)
[18:59:45] [Craft Scheduler Thread - 441/WARN]: 	at me.Fupery.ArtMap.IO.ArtDatabase$QueuedQuery.execute(ArtDatabase.java:349)
[18:59:45] [Craft Scheduler Thread - 441/WARN]: 	at me.Fupery.ArtMap.IO.ArtDatabase.getArtwork(ArtDatabase.java:123)
[18:59:45] [Craft Scheduler Thread - 441/WARN]: 	at me.Fupery.ArtMap.Easel.EaselEvent.editArtwork(EaselEvent.java:99)
[18:59:45] [Craft Scheduler Thread - 441/WARN]: 	at me.Fupery.ArtMap.Easel.EaselEvent.lambda$callEvent$0(EaselEvent.java:71)
[18:59:45] [Craft Scheduler Thread - 441/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)
[18:59:45] [Craft Scheduler Thread - 441/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[18:59:45] [Craft Scheduler Thread - 441/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:59:45] [Craft Scheduler Thread - 441/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[18:59:45] [Craft Scheduler Thread - 441/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[18:59:45] [Craft Scheduler Thread - 441/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

ArtMap error.log
```
2016-12-15 16:40:26
[VERSION]:git-Paper-963 (MC: 1.11), ArtMap v2.5
---------------------[SERVER]---------------------
Loaded Plugins: [Big list of Plugins]
Plugin compatability hooks: WorldGuardCompat [LOADED:true], Reflection Handler: class me.Fupery.ArtMap.Compatability.VanillaReflectionHandler
--------------------[STACKTRACE]---------------------
[SQLITE_CONSTRAINT_UNIQUE]  A UNIQUE constraint failed (UNIQUE constraint failed: artworks.id)
org.sqlite.core.DB.newSQLException(DB.java:909)
org.sqlite.core.DB.newSQLException(DB.java:921)
org.sqlite.core.DB.execute(DB.java:825)
org.sqlite.core.DB.executeUpdate(DB.java:863)
org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:99)
me.Fupery.ArtMap.IO.ArtDatabase$QueuedStatement.execute(ArtDatabase.java:306)
me.Fupery.ArtMap.IO.ArtDatabase.addArtwork(ArtDatabase.java:250)
me.Fupery.ArtMap.IO.MapArt.lambda$saveArtwork$0(MapArt.java:75)
org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)
org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)



2016-12-15 17:09:14
[VERSION]:git-Paper-963 (MC: 1.11), ArtMap v2.5
---------------------[SERVER]---------------------
Loaded Plugins: [Big list of Plugins]
Plugin compatability hooks: WorldGuardCompat [LOADED:true], Reflection Handler: class me.Fupery.ArtMap.Compatability.VanillaReflectionHandler
--------------------[STACKTRACE]---------------------
The database has been closed
org.sqlite.core.NativeDB.throwex(NativeDB.java:471)
org.sqlite.core.NativeDB.column_text_utf8(Native Method)
org.sqlite.core.NativeDB.column_text(NativeDB.java:242)
org.sqlite.jdbc3.JDBC3ResultSet.getString(JDBC3ResultSet.java:436)
org.sqlite.jdbc3.JDBC3ResultSet.getString(JDBC3ResultSet.java:443)
me.Fupery.ArtMap.IO.ArtDatabase.readArtwork(ArtDatabase.java:127)
me.Fupery.ArtMap.IO.ArtDatabase.access$100(ArtDatabase.java:14)
me.Fupery.ArtMap.IO.ArtDatabase$2.read(ArtDatabase.java:121)
me.Fupery.ArtMap.IO.ArtDatabase$2.read(ArtDatabase.java:112)
me.Fupery.ArtMap.IO.ArtDatabase$QueuedQuery.execute(ArtDatabase.java:345)
me.Fupery.ArtMap.IO.ArtDatabase.getArtwork(ArtDatabase.java:123)
me.Fupery.ArtMap.Easel.EaselEvent.editArtwork(EaselEvent.java:99)
me.Fupery.ArtMap.Easel.EaselEvent.lambda$callEvent$0(EaselEvent.java:71)
org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)
org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)



2016-12-17 18:59:45
[VERSION]:git-Paper-968 (MC: 1.11), ArtMap v2.5
---------------------[SERVER]---------------------
Loaded Plugins: [Big list of Plugins]
Plugin compatability hooks: WorldGuardCompat [LOADED:true], Reflection Handler: class me.Fupery.ArtMap.Compatability.VanillaReflectionHandler
--------------------[STACKTRACE]---------------------
The prepared statement has been finalized
org.sqlite.core.NativeDB.throwex(NativeDB.java:471)
org.sqlite.core.NativeDB.reset(Native Method)
org.sqlite.jdbc3.JDBC3PreparedStatement.executeQuery(JDBC3PreparedStatement.java:72)
me.Fupery.ArtMap.IO.ArtDatabase$QueuedQuery.execute(ArtDatabase.java:345)
me.Fupery.ArtMap.IO.ArtDatabase.getArtwork(ArtDatabase.java:123)
me.Fupery.ArtMap.Easel.EaselEvent.editArtwork(EaselEvent.java:99)
me.Fupery.ArtMap.Easel.EaselEvent.lambda$callEvent$0(EaselEvent.java:71)
org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)
org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)
```

Java crash log.
http://paste.ubuntu.com/23646601/
```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 23501  org.sqlite.core.NativeDB.reset(J)I (0 bytes) @ 0x0000705e512b71f0 [0x0000705e512b71a0+0x50]
J 49744 C2 org.sqlite.core.CoreStatement.internalClose()V (75 bytes) @ 0x0000705e5335b918 [0x0000705e5335b7e0+0x138]
J 27743 C1 org.sqlite.jdbc3.JDBC3Statement.close()V (37 bytes) @ 0x0000705e5160e664 [0x0000705e5160e420+0x244]
J 27742 C1 org.sqlite.jdbc4.JDBC4Statement.close()V (10 bytes) @ 0x0000705e4dbce764 [0x0000705e4dbce6c0+0xa4]
J 47720 C1 me.Fupery.ArtMap.IO.ArtDatabase$QueuedQuery.close(Ljava/sql/Connection;Ljava/sql/PreparedStatement;)V (37 bytes) @ 0x0000705e4d47155c [0x0000705e4d4713e0+0x17c]
J 47741 C1 me.Fupery.ArtMap.IO.ArtDatabase$QueuedQuery.execute(Ljava/lang/String;)Ljava/lang/Object; (81 bytes) @ 0x0000705e54594024 [0x0000705e54593a20+0x604]
j  me.Fupery.ArtMap.IO.ArtDatabase.getArtwork(S)Lme/Fupery/ArtMap/IO/MapArt;+11
j  me.Fupery.ArtMap.Easel.EaselEvent.editArtwork(Lorg/bukkit/inventory/ItemStack;)V+7
j  me.Fupery.ArtMap.Easel.EaselEvent.lambda$callEvent$0()V+10
j  me.Fupery.ArtMap.Easel.EaselEvent$$Lambda$117.run()V+4
J 24222 C2 org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run()V (750 bytes) @ 0x0000705e4e03ae40 [0x0000705e4e03a8a0+0x5a0]
J 23691 C2 com.destroystokyo.paper.ServerSchedulerReportingWrapper.run()V (97 bytes) @ 0x0000705e4d2df25c [0x0000705e4d2df200+0x5c]
J 28717 C2 java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V (225 bytes) @ 0x0000705e5218257c [0x0000705e521823e0+0x19c]
J 41355 C1 java.util.concurrent.ThreadPoolExecutor$Worker.run()V (9 bytes) @ 0x0000705e4d19bc3c [0x0000705e4d19bb00+0x13c]
J 36728 C1 java.lang.Thread.run()V (17 bytes) @ 0x0000705e52edecfc [0x0000705e52edeb80+0x17c]
v  ~StubRoutines::call_stub
```

**Comment by mibby** [comment]
@Fupery Was able to reproduce a server crash again with ArtMap. 

Paper dev 991 (MC / Spigot 1.11.2)
ArtMap v2.5

* I spawned in an easel and canvas.
* Painted something small very quickly.
* Saved the canvas as test.
* Then tried throwing the saved canvas back on an easel.
* The painting didn't show up on the easel so I took it off and tried re-placing it immediately again.
* Server crashed.

Java crash log.
http://paste.ubuntu.com/23678940/
```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 21566  org.sqlite.core.NativeDB.reset(J)I (0 bytes) @ 0x00006ee09ed4bf70 [0x00006ee09ed4bf20+0x50]
J 26005 C1 org.sqlite.core.CoreResultSet.close()V (110 bytes) @ 0x00006ee09f31c8d4 [0x00006ee09f31c640+0x294]
J 26004 C1 org.sqlite.jdbc4.JDBC4ResultSet.close()V (50 bytes) @ 0x00006ee09e818394 [0x00006ee09e818240+0x154]
J 29139 C1 org.sqlite.core.CoreStatement.internalClose()V (75 bytes) @ 0x00006ee09edd0a74 [0x00006ee09edcfae0+0xf94]
J 29935 C1 org.sqlite.jdbc3.JDBC3Statement.close()V (37 bytes) @ 0x00006ee0a1007924 [0x00006ee0a10076e0+0x244]
J 29934 C1 org.sqlite.jdbc4.JDBC4Statement.close()V (10 bytes) @ 0x00006ee0a0e1d564 [0x00006ee0a0e1d4c0+0xa4]
j  me.Fupery.ArtMap.IO.ArtDatabase$QueuedQuery.close(Ljava/sql/Connection;Ljava/sql/PreparedStatement;)V+5
j  me.Fupery.ArtMap.IO.ArtDatabase$QueuedQuery.execute(Ljava/lang/String;)Ljava/lang/Object;+43
j  me.Fupery.ArtMap.IO.ArtDatabase.getArtwork(S)Lme/Fupery/ArtMap/IO/MapArt;+11
j  me.Fupery.ArtMap.Easel.EaselEvent.editArtwork(Lorg/bukkit/inventory/ItemStack;)V+7
j  me.Fupery.ArtMap.Easel.EaselEvent.lambda$callEvent$0()V+10
j  me.Fupery.ArtMap.Easel.EaselEvent$$Lambda$123.run()V+4
J 23977 C2 org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run()V (750 bytes) @ 0x00006ee0a118acf4 [0x00006ee0a118a760+0x594]
J 23987 C2 com.destroystokyo.paper.ServerSchedulerReportingWrapper.run()V (97 bytes) @ 0x00006ee0a12f375c [0x00006ee0a12f3700+0x5c]
J 27318 C2 java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V (225 bytes) @ 0x00006ee0a0f097c8 [0x00006ee0a0f09640+0x188]
J 36919 C1 java.util.concurrent.ThreadPoolExecutor$Worker.run()V (9 bytes) @ 0x00006ee09d51a13c [0x00006ee09d51a000+0x13c]
J 33124 C1 java.lang.Thread.run()V (17 bytes) @ 0x00006ee0a280303c [0x00006ee0a2802ec0+0x17c]
v  ~StubRoutines::call_stub
```

**Comment by Fupery** [comment]
The issue is that the map ID being saved is already found in the database; I'll just have to catch and handle this situation.

**Comment by mibby** [comment]
Including the 3 separate error logs in the artmap error log file? Those seem to be all slightly different and unrelated to the crashing?
