### ISSUE TITLE
can't paint

### ISSUE THREAD

**Issue by zeddy4** [Fupery/ArtMap#32]
when I place a easel it places with a firework in it and can I can't break it or paint on it please help this plugin worked before

console error =

[06:45:07] [Server thread/ERROR]: Could not pass event PlayerInteractAtEntityEvent to ArtMap v2.4.8
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1518) [spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:69) [spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:13) [spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.v1_11_R1.EntityItemFrame.setItem(EntityItemFrame.java:118) ~[spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
	at net.minecraft.server.v1_11_R1.EntityItemFrame.setItem(EntityItemFrame.java:114) ~[spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftItemFrame.setItem(CraftItemFrame.java:53) ~[spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
	at me.Fupery.ArtMap.Easel.Easel.removeItem(Easel.java:206) ~[?:?]
	at me.Fupery.ArtMap.Easel.EaselEvent.callEvent(EaselEvent.java:57) ~[?:?]
	at me.Fupery.ArtMap.Listeners.PlayerInteractEaselListener.callEaselEvent(PlayerInteractEaselListener.java:105) ~[?:?]
	at me.Fupery.ArtMap.Listeners.PlayerInteractEaselListener.onPlayerInteractAtEntity(PlayerInteractEaselListener.java:35) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor753.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
	... 15 more

**Comment by Fupery** [comment]
When does this error come up? When you first place the easel, or when you try to put a canvas on it?

**Comment by zeddy4** [comment]
when I  try to paint

**Comment by Fupery** [comment]
Could you provide me with your ArtMap version, and a list of plugins you're using?

**Comment by zeddy4** [comment]
ok latest version 
advanced reporter, world edit, colored signs, rays bans, skript, essentials, essentials chat, vehicles, clear lag, MafiaCraftCorePlugin(Custom only includes sending messages to players as of now) ,heads ,food mc ,vault world guard, wiipay, title manager, area shop, lottery and art map.

**Comment by zeddy4** [comment]
also, I am trying on a different server and its when I try to place canvas.
and the error might be different
[20:01:20 ERROR]: Could not pass event PlayerInteractAtEntityEvent to ArtMap v2.6.2
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-54ec0b8-7b044de]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-54ec0b8-7b044de]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-54ec0b8-7b044de]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-54ec0b8-7b044de]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1537) [spigot-1.11.2.jar:git-Spigot-54ec0b8-7b044de]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:69) [spigot-1.11.2.jar:git-Spigot-54ec0b8-7b044de]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-54ec0b8-7b044de]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-54ec0b8-7b044de]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-54ec0b8-7b044de]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2.jar:git-Spigot-54ec0b8-7b044de]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-54ec0b8-7b044de]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-54ec0b8-7b044de]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-54ec0b8-7b044de]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.IllegalArgumentException: World cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot-1.11.2.jar:git-Spigot-54ec0b8-7b044de]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.createMap(CraftServer.java:1264) ~[spigot-1.11.2.jar:git-Spigot-54ec0b8-7b044de]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.createMap(CraftServer.java:1) ~[spigot-1.11.2.jar:git-Spigot-54ec0b8-7b044de]
        at org.bukkit.Bukkit.createMap(Bukkit.java:533) ~[spigot-1.11.2.jar:git-Spigot-54ec0b8-7b044de]
        at me.Fupery.ArtMap.IO.Database.Database.createMap(Database.java:143) ~[?:?]
        at me.Fupery.ArtMap.Easel.EaselEvent.callEvent(EaselEvent.java:55) ~[?:?]
        at me.Fupery.ArtMap.Listeners.PlayerInteractEaselListener.callEaselEvent(PlayerInteractEaselListener.java:100) ~[?:?]
        at me.Fupery.ArtMap.Listeners.PlayerInteractEaselListener.onPlayerInteractAtEntity(PlayerInteractEaselListener.java:32) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor99.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-54ec0b8-7b044de]
        ... 15 more

**Comment by zeddy4** [comment]
and for the 1st bug report the plugins were the same more or less

**Comment by zeddy4** [comment]
version 2.4.8

**Comment by Fupery** [comment]
For the first issue, download the [ProtocolLib plugin](https://www.spigotmc.org/resources/protocollib.1997/) and add it to your server plugins folder.

That second issue was a bug with ArtMap 2.6.1, it was fixed in version 2.6.2, which you can download [here](https://www.spigotmc.org/resources/artmap-make-custom-textures-and-paintings-with-no-resource-pack-✍.26667/).

**Comment by zeddy4** [comment]
sorry to say but this didn't work

**Comment by zeddy4** [comment]
[12:08:54 ERROR]: Could not pass event PlayerInteractAtEntityEvent to ArtMap v2.6.2
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-9ba269b-c19c293]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-9ba269b-c19c293]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-9ba269b-c19c293]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-9ba269b-c19c293]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1537) [spigot-1.11.2.jar:git-Spigot-9ba269b-c19c293]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:69) [spigot-1.11.2.jar:git-Spigot-9ba269b-c19c293]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-9ba269b-c19c293]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-9ba269b-c19c293]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-9ba269b-c19c293]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2.jar:git-Spigot-9ba269b-c19c293]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-9ba269b-c19c293]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-9ba269b-c19c293]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-9ba269b-c19c293]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.IllegalArgumentException: World cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot-1.11.2.jar:git-Spigot-9ba269b-c19c293]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.createMap(CraftServer.java:1264) ~[spigot-1.11.2.jar:git-Spigot-9ba269b-c19c293]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.createMap(CraftServer.java:1) ~[spigot-1.11.2.jar:git-Spigot-9ba269b-c19c293]
        at org.bukkit.Bukkit.createMap(Bukkit.java:533) ~[spigot-1.11.2.jar:git-Spigot-9ba269b-c19c293]
        at me.Fupery.ArtMap.IO.Database.Database.createMap(Database.java:143) ~[?:?]
        at me.Fupery.ArtMap.Easel.EaselEvent.callEvent(EaselEvent.java:55) ~[?:?]
        at me.Fupery.ArtMap.Listeners.PlayerInteractEaselListener.callEaselEvent(PlayerInteractEaselListener.java:100) ~[?:?]
        at me.Fupery.ArtMap.Listeners.PlayerInteractEaselListener.onPlayerInteractAtEntity(PlayerInteractEaselListener.java:32) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-9ba269b-c19c293]
        ... 15 more

**Comment by zeddy4** [comment]
same error

**Comment by zeddy4** [comment]
also I can't remove the paintings

**Comment by Fupery** [comment]
Do you have a custom name for the world you're using artmap in? In your config.yml you need to set the world up:
```YAML 
world: your_world
```

**Comment by kieran737** [comment]
That fixed it for me, thanks for posting.

**Comment by HongMint88** [comment]
> That fixed it for me, thanks for posting.

I'm having the same problem, can you tell me how you solved it?

**Comment by OpalMoonstride** [comment]
> > That fixed it for me, thanks for posting.
> 
> I'm having the same problem, can you tell me how you solved it?

This github is dead, as Fupery has not touched ArtMap since 2017. If you are using a current version of ArtMap it is nothing like the original. 

If you are using the original ArtMap, from 2017, the person above stated, "That fixed it for me, thanks for posting" in reference to adding "world: your_world" in the config.yml. 

If you still need help, please visit the current gitlab (https://gitlab.com/BlockStack/ArtMap/-/wikis/home), open a new ticket, fill out the questions, and I can see if I can help.
