### ISSUE TITLE
Could not pass event PlayerInteractAtEntityEvent to ArtMap

### ISSUE THREAD

**Issue by mibby** [Fupery/ArtMap#47]
Compiled source as of this branch and commit.
https://github.com/Fupery/ArtMap/commit/64e7c9d2f10b39f5272591bcb3a366e685144a39

```
[12:03:44] [Server thread/ERROR]: Could not pass event PlayerInteractAtEntityEvent to ArtMap v2.6.2
org.bukkit.event.EventException
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.11.2.jar:git-Paper-1087]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.11.2.jar:git-Paper-1087]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.2.jar:git-Paper-1087]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[patched_1.11.2.jar:git-Paper-1087]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[patched_1.11.2.jar:git-Paper-1087]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1576) ~[patched_1.11.2.jar:git-Paper-1087]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.11.2.jar:git-Paper-1087]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.11.2.jar:git-Paper-1087]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.11.2.jar:git-Paper-1087]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [patched_1.11.2.jar:git-Paper-1087]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:830) [patched_1.11.2.jar:git-Paper-1087]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1087]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [patched_1.11.2.jar:git-Paper-1087]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [patched_1.11.2.jar:git-Paper-1087]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at me.Fupery.ArtMap.Utils.Reflection.getField(Reflection.java:44) ~[?:?]
	at me.Fupery.ArtMap.Utils.Reflection.setWorldMap(Reflection.java:219) ~[?:?]
	at me.Fupery.ArtMap.IO.Database.Database.createMap(Database.java:138) ~[?:?]
	at me.Fupery.ArtMap.Easel.EaselEvent.callEvent(EaselEvent.java:55) ~[?:?]
	at me.Fupery.ArtMap.Listeners.PlayerInteractEaselListener.callEaselEvent(PlayerInteractEaselListener.java:100) ~[?:?]
	at me.Fupery.ArtMap.Listeners.PlayerInteractEaselListener.onPlayerInteractAtEntity(PlayerInteractEaselListener.java:32) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[patched_1.11.2.jar:git-Paper-1087]
	... 16 more
[12:03:45] [Server thread/ERROR]: Could not pass event PlayerInteractAtEntityEvent to ArtMap v2.6.2
org.bukkit.event.EventException
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.11.2.jar:git-Paper-1087]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.11.2.jar:git-Paper-1087]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.2.jar:git-Paper-1087]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[patched_1.11.2.jar:git-Paper-1087]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[patched_1.11.2.jar:git-Paper-1087]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1576) ~[patched_1.11.2.jar:git-Paper-1087]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.11.2.jar:git-Paper-1087]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.11.2.jar:git-Paper-1087]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.11.2.jar:git-Paper-1087]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [patched_1.11.2.jar:git-Paper-1087]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:830) [patched_1.11.2.jar:git-Paper-1087]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1087]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [patched_1.11.2.jar:git-Paper-1087]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [patched_1.11.2.jar:git-Paper-1087]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at me.Fupery.ArtMap.Utils.Reflection.getField(Reflection.java:44) ~[?:?]
	at me.Fupery.ArtMap.Utils.Reflection.setWorldMap(Reflection.java:219) ~[?:?]
	at me.Fupery.ArtMap.IO.Database.Database.createMap(Database.java:138) ~[?:?]
	at me.Fupery.ArtMap.Easel.EaselEvent.callEvent(EaselEvent.java:55) ~[?:?]
	at me.Fupery.ArtMap.Listeners.PlayerInteractEaselListener.callEaselEvent(PlayerInteractEaselListener.java:100) ~[?:?]
	at me.Fupery.ArtMap.Listeners.PlayerInteractEaselListener.onPlayerInteractAtEntity(PlayerInteractEaselListener.java:32) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[patched_1.11.2.jar:git-Paper-1087]
	... 16 more
```

**Comment by Tikistand** [comment]
I've also got this issue. Doesn't seem to be a plugin conflict issue either.

**Comment by Fupery** [comment]
Looks like this is an issue with PaperMC - ArtMap is only supported for official spigot builds, it won't work with third party forks.

**Comment by Tikistand** [comment]
`[11:52:40] [Server thread/ERROR]: Could not pass event PlayerInteractAtEntityEvent to ArtMap v2.6.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1537) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:69) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:13) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.IllegalArgumentException: World cannot be null
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.createMap(CraftServer.java:1264) ~[spigot.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.createMap(CraftServer.java:1) ~[spigot.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.Bukkit.createMap(Bukkit.java:533) ~[spigot.jar:git-Spigot-3fb9445-2b6c9f4]
	at me.Fupery.ArtMap.IO.Database.Database.createMap(Database.java:143) ~[?:?]
	at me.Fupery.ArtMap.Easel.EaselEvent.callEvent(EaselEvent.java:55) ~[?:?]
	at me.Fupery.ArtMap.Listeners.PlayerInteractEaselListener.callEaselEvent(PlayerInteractEaselListener.java:100) ~[?:?]
	at me.Fupery.ArtMap.Listeners.PlayerInteractEaselListener.onPlayerInteractAtEntity(PlayerInteractEaselListener.java:32) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-3fb9445-2b6c9f4]
	... 15 more
`

Same issue both on Spigot and PaperSpigot.

**Comment by PieGuy128** [comment]
Tried with latest Paper and Spigot, using code from git tree - can't reproduce
