### ISSUE TITLE
MC 1.12 Support

### ISSUE THREAD

**Issue by mibby** [Fupery/ArtMap#51]
@Fupery Just a heads up that ArtMap breaks on 1.12. :)

**Comment by mibby** [comment]
Error on official 1.12 release build.

```
[21:29:16] [Server thread/INFO]: [ArtMap] Enabling ArtMap v2.6.2
[21:29:16] [Server thread/INFO]: [ArtMap] WorldGuard hooks enabled.
[21:29:16] [Server thread/INFO]: [ArtMap] ProtocolLib hooks enabled.
[21:29:16] [Server thread/INFO]: [ArtMap] Loading 'english' language file
[21:29:16] [Server thread/ERROR]: Error occurred while enabling ArtMap v2.6.2 (Is it up to date?)
com.comphenix.protocol.reflect.FieldAccessException: No field with type byte exists in class PacketPlayOutChat.
	at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:348) ~[?:?]
	at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:328) ~[?:?]
	at me.Fupery.ArtMap.IO.Protocol.Out.ProtocolLibSender.buildChatPacket(ProtocolLibSender.java:17) ~[?:?]
	at me.Fupery.ArtMap.Config.Lang.load(Lang.java:44) ~[?:?]
	at me.Fupery.ArtMap.ArtMap.onEnable(ArtMap.java:130) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.jar:git-Paper-1106]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.jar:git-Paper-1106]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.jar:git-Paper-1106]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:379) [patched_1.12.jar:git-Paper-1106]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329) [patched_1.12.jar:git-Paper-1106]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:438) [patched_1.12.jar:git-Paper-1106]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:399) [patched_1.12.jar:git-Paper-1106]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [patched_1.12.jar:git-Paper-1106]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.12.jar:git-Paper-1106]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:612) [patched_1.12.jar:git-Paper-1106]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
[21:29:16] [Server thread/INFO]: [ArtMap] Disabling ArtMap v2.6.2
[21:29:16] [Server thread/ERROR]: Error occurred while disabling ArtMap v2.6.2 (Is it up to date?)
java.lang.NullPointerException: null
	at me.Fupery.ArtMap.ArtMap.onDisable(ArtMap.java:153) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.12.jar:git-Paper-1106]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [patched_1.12.jar:git-Paper-1106]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320) [patched_1.12.jar:git-Paper-1106]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.jar:git-Paper-1106]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:379) [patched_1.12.jar:git-Paper-1106]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329) [patched_1.12.jar:git-Paper-1106]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:438) [patched_1.12.jar:git-Paper-1106]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:399) [patched_1.12.jar:git-Paper-1106]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [patched_1.12.jar:git-Paper-1106]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.12.jar:git-Paper-1106]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:612) [patched_1.12.jar:git-Paper-1106]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
```

**Comment by mibby** [comment]
As well as compiling the source against Spigot 1.12 and ProtocolLib 4.3.0;

```
[08:35:25] [Server thread/ERROR]: Error occurred while enabling ArtMap v2.6.2 (Is it up to date?)
com.comphenix.protocol.reflect.FieldAccessException: No field with type byte exists in class PacketPlayOutChat.
	at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:348) ~[?:?]
	at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:328) ~[?:?]
	at me.Fupery.ArtMap.IO.Protocol.Out.ProtocolLibSender.buildChatPacket(ProtocolLibSender.java:17) ~[?:?]
	at me.Fupery.ArtMap.Config.Lang.load(Lang.java:44) ~[?:?]
	at me.Fupery.ArtMap.ArtMap.onEnable(ArtMap.java:130) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.jar:git-Paper-1111]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.jar:git-Paper-1111]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.jar:git-Paper-1111]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:379) [patched_1.12.jar:git-Paper-1111]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329) [patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:438) [patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:399) [patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:612) [patched_1.12.jar:git-Paper-1111]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
[08:35:25] [Server thread/INFO]: [ArtMap] Disabling ArtMap v2.6.2
[08:35:25] [Server thread/ERROR]: Error occurred while disabling ArtMap v2.6.2 (Is it up to date?)
java.lang.NullPointerException: null
	at me.Fupery.ArtMap.ArtMap.onDisable(ArtMap.java:153) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.12.jar:git-Paper-1111]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [patched_1.12.jar:git-Paper-1111]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320) [patched_1.12.jar:git-Paper-1111]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.jar:git-Paper-1111]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:379) [patched_1.12.jar:git-Paper-1111]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329) [patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:438) [patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:399) [patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:612) [patched_1.12.jar:git-Paper-1111]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
```

**Comment by Fupery** [comment]
Supported in 2.6.4
