### ISSUE TITLE
IllegalPluginAccessException: Plugin attempted to register task while disabled

### ISSUE THREAD

**Issue by mibby** [Fupery/ArtMap#53]
```
[15:50:13] [Server thread/INFO]: [ArtMap] Disabling ArtMap v2.6.7
[15:50:13] [Server thread/ERROR]: Error occurred while disabling ArtMap v2.6.7 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:413) ~[patched_1.12.jar:git-Paper-1132]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:148) ~[patched_1.12.jar:git-Paper-1132]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:122) ~[patched_1.12.jar:git-Paper-1132]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:105) ~[patched_1.12.jar:git-Paper-1132]
	at me.Fupery.ArtMap.Utils.Scheduler$2.run(Scheduler.java:37) ~[?:?]
	at me.Fupery.ArtMap.IO.Database.Database.accessSQL(Database.java:199) ~[?:?]
	at me.Fupery.ArtMap.IO.Database.Database.cacheMap(Database.java:150) ~[?:?]
	at me.Fupery.ArtMap.Painting.ArtSession.persistMap(ArtSession.java:138) ~[?:?]
	at me.Fupery.ArtMap.Painting.ArtSession.end(ArtSession.java:129) ~[?:?]
	at me.Fupery.ArtMap.Painting.ArtistHandler.removePlayer(ArtistHandler.java:81) ~[?:?]
	at me.Fupery.ArtMap.Painting.ArtistHandler.clearPlayers(ArtistHandler.java:95) ~[?:?]
	at me.Fupery.ArtMap.Painting.ArtistHandler.stop(ArtistHandler.java:104) ~[?:?]
	at me.Fupery.ArtMap.ArtMap.onDisable(ArtMap.java:158) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.12.jar:git-Paper-1132]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [patched_1.12.jar:git-Paper-1132]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [patched_1.12.jar:git-Paper-1132]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [patched_1.12.jar:git-Paper-1132]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:348) [patched_1.12.jar:git-Paper-1132]
	at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:485) [patched_1.12.jar:git-Paper-1132]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:700) [patched_1.12.jar:git-Paper-1132]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by Fupery** [comment]
A fix for this will be released in ArtMap 2.6.11
