### ISSUE TITLE
IllegalArgumentException: Cannot drop AIR

### ISSUE THREAD

**Issue by mibby** [Fupery/ArtMap#56]
```
[13:40:47] [Server thread/ERROR]: Could not pass event PlayerInteractAtEntityEvent to ArtMap v2.6.7
org.bukkit.event.EventException: null
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.12.jar:git-Paper-1133]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.jar:git-Paper-1133]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.jar:git-Paper-1133]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) ~[patched_1.12.jar:git-Paper-1133]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) ~[patched_1.12.jar:git-Paper-1133]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1614) ~[patched_1.12.jar:git-Paper-1133]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.12.jar:git-Paper-1133]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.12.jar:git-Paper-1133]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.jar:git-Paper-1133]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.jar:git-Paper-1133]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842) [patched_1.12.jar:git-Paper-1133]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) [patched_1.12.jar:git-Paper-1133]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766) [patched_1.12.jar:git-Paper-1133]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664) [patched_1.12.jar:git-Paper-1133]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.IllegalArgumentException: Cannot drop AIR.
	at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[patched_1.12.jar:git-Paper-1133]
	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.dropItem(CraftWorld.java:330) ~[patched_1.12.jar:git-Paper-1133]
	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.dropItemNaturally(CraftWorld.java:372) ~[patched_1.12.jar:git-Paper-1133]
	at me.Fupery.ArtMap.Painting.ArtSession.addKit(ArtSession.java:99) ~[?:?]
	at me.Fupery.ArtMap.Painting.ArtSession.start(ArtSession.java:57) ~[?:?]
	at me.Fupery.ArtMap.Painting.ArtistHandler.addPlayer(ArtistHandler.java:55) ~[?:?]
	at me.Fupery.ArtMap.Easel.EaselEvent.callEvent(EaselEvent.java:42) ~[?:?]
	at me.Fupery.ArtMap.Listeners.PlayerInteractEaselListener.callEaselEvent(PlayerInteractEaselListener.java:100) ~[?:?]
	at me.Fupery.ArtMap.Listeners.PlayerInteractEaselListener.onPlayerInteractAtEntity(PlayerInteractEaselListener.java:32) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[patched_1.12.jar:git-Paper-1133]
	... 16 more
```

**Comment by Fupery** [comment]
Fixed in the upcoming version 2.6.11
