### ISSUE TITLE
It does not work to save a drawing through "PaintBrush", you can save through the command.

### ISSUE THREAD

**Issue by vayner25** [Fupery/ArtMap#87]
[03:52:25 WARN]: [ArtMap] Task #265608 for ArtMap v3.9.14 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class me.fupery.shade.AnvilGUI
        at me.fupery.shade.AnvilGUI$Builder.<init>(AnvilGUI.java:385) ~[ArtMap-3.9.14.jar:?]
        at me.Fupery.ArtMap.Painting.ArtistHandler.lambda$handlePaintBrush$3(ArtistHandler.java:89) ~[ArtMap-3.9.14.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1646) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1525) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
        at java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalStateException: AnvilGUI does not support server version "1_20_R3" [in thread "Server thread"]
        at me.fupery.shade.version.VersionMatcher.match(VersionMatcher.java:32) ~[ArtMap-3.9.14.jar:?]
        at me.fupery.shade.AnvilGUI.<clinit>(AnvilGUI.java:43) ~[ArtMap-3.9.14.jar:?]
        ... 10 more
>

**Comment by vayner25** [comment]
Version my server - 1.20.4 JDK 22

**Comment by vayner25** [comment]
And the command /artmap reload does not work

**Comment by vayner25** [comment]
By the way your plugin was very hard to find, why don't you put it on Spigot ?

**Comment by OpalMoonstride** [comment]
> [03:52:25 WARN]: [ArtMap] Task #265608 for ArtMap v3.9.14 generated an exception java.lang.NoClassDefFoundError: Could not initialize class me.fupery.shade.AnvilGUI at me.fupery.shade.AnvilGUI$Builder.(AnvilGUI.java:385) ~[ArtMap-3.9.14.jar:?] at me.Fupery.ArtMap.Painting.ArtistHandler.lambda$handlePaintBrush$3(ArtistHandler.java:89) ~[ArtMap-3.9.14.jar:?] at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-496] at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.4.jar:git-Paper-496] at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1646) ~[paper-1.20.4.jar:git-Paper-496] at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-496] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1525) ~[paper-1.20.4.jar:git-Paper-496] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-496] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496] at java.lang.Thread.run(Thread.java:1570) ~[?:?] Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalStateException: AnvilGUI does not support server version "1_20_R3" [in thread "Server thread"] at me.fupery.shade.version.VersionMatcher.match(VersionMatcher.java:32) ~[ArtMap-3.9.14.jar:?] at me.fupery.shade.AnvilGUI.(AnvilGUI.java:43) ~[ArtMap-3.9.14.jar:?] ... 10 more
> 
> >

How did you manage to get my fork and still post an issue on github instead of on gitlab, where I have my fork? Fupery is MIA. Possibly passed away, as no one has ever heard from them since 1.12. You should post in the proper place, on gitlab. Please make sure you complete the template I made.

 I also have an FAQ on my fork which answers your last question.  [Here](https://gitlab.com/BlockStack/ArtMap/-/wikis/FAQ)
![image](https://github.com/Fupery/ArtMap/assets/39387146/93e3f655-18c3-42f5-a8d2-31d5483a1f4e)

I also have more detailed answer in issue 235 on gitlab.
